### ISSUE TITLE
Update audit data

### ISSUE THREAD

**Issue by azakolyukina** [iangow/wrds_pg#22] opened 2017-08-15 21:37 UTC
@jingyujzhang (CC @iangow): 

Could you please fork this repository and update code for `audit` schema (see `audit` folder) and update data in `audit` schema on `aaz` machine for the following data:
* Late filings in [AuditAnalytics - Non-timely Filer Information And Analysis](https://wrds-web.wharton.upenn.edu/wrds/ds/audit/nt/index.cfm?navId=2)
* D&O change data in [AuditAnalytics - Director and Officer Changes](https://wrds-web.wharton.upenn.edu/wrds/ds/audit/diroffichange/index.cfm?navId=2)
* Litigation [AuditAnalytics - Legal Case And Legal Parties](https://wrds-web.wharton.upenn.edu/wrds/ds/audit/auditlegal/index.cfm?navId=3)
* Auditor changes [AuditAnalytics - Auditor Changes](https://wrds-web.wharton.upenn.edu/wrds/ds/audit/auditchange/index.cfm?navId=2)
* Wells notices --- @azakolyukina ask Olya
* Bankruptcy [AuditAnalytics - Bankruptcy Notification](https://wrds-web.wharton.upenn.edu/wrds/ds/audit/bankrupt/index.cfm?navId=3)
* Internal control weaknesses [AuditAnalytics - SOX 302 Disclosure Controls](https://wrds-web.wharton.upenn.edu/wrds/ds/audit/auditsox302/index.cfm?navId=2)  and [AuditAnalytics - SOX 404 Internal Controls](https://wrds-web.wharton.upenn.edu/wrds/ds/audit/auditsox404/index.cfm?navId=2)

Set ownership to `audit`

**Comment by iangow** [comment] 2017-08-15 21:47
Looking at the data (to which I now have access), I think it makes sense to eliminate a lot of junk variables that WRDS adds to the tables. I think WRDS merges a whole bunch of tables to create the data … we'd really prefer the underlying tables.

We'd probably want to source the data in `HIWATER_`, `LATEST`, `MATCH`, `PRIORFY`, etc., from Compustat. So I think it makes sense to ditch those variables. My code already does that to some extent.

The underlying tables do seem to be available as "`feed`" tables. But effort would be needed to work out where the various pieces come from.

**Comment by azakolyukina** [comment] 2017-08-15 21:53
> Looking at the data (to which I now have access), I think it makes sense to eliminate a lot of junk variables that WRDS adds to the tables. I think WRDS merges a whole bunch of tables to create the data … we'd really prefer the underlying tables.

I believe AuditAnalytics does it. I download their advanced restatements feed directly which has a lot of the same variables that I never use. 

> We'd probably want to source the data in HIWATER_, LATEST, MATCH, PRIORFY, etc., from Compustat. So I think it makes sense to ditch those variables. My code already does that to some extent.

Yes, I think fewer relevant columns is better. 


> The underlying tables do seem to be available as "feed" tables. But effort would be needed to work out where the various pieces come from.

As I mentioned before, the main `feed` tables have the same structure. I actually talked to them about getting access to litigation `feed` and was (strongly) suggested that I should just get this data from WRDS because the data is identical. I could probably try to push again if there is a very specific reason for doing that.

**Comment by iangow** [comment] 2017-08-15 21:59
> Wells notices --- @azakolyukina ask Olya

If these come from a source other than Audit Analytics, I would put the code in a separate repository.

The Audit Analytics data, which requires a lot more work than the other WRDS data libraries I've used, almost warrants its own schema. But given that it relies on the `wrds_update.py` code and this may change over time (e.g., if WRDS changes things), it's probably better to keep it all in one place.

Note that things are a little messy in this repository now for a few reasons:

1. I have legacy Perl code and newer Python code. I would lean to using the Python code, but I think some things don't yet work with that.
2. I haven't worked out an easy way to be able to put the Python code in a subdirectory and still access the main code. So all the new code now clutters the main directory.
3. The code isn't as well documented as it should be. If you encounter things worth documenting, please add to the `readme.md` (this should really relate to the Python code, not the older Perl code).

**Comment by iangow** [comment] 2017-08-15 22:10
> The Audit Analytics data, which requires a lot more work than the other WRDS data libraries I've used, almost warrants its own schema.

I meant to say:

> The Audit Analytics data, which requires a lot more work than the other WRDS data libraries I've used, almost warrants its own ***repository***.

**Comment by jingyujzhang** [comment] 2017-08-16 22:26
@iangow: I am not assigned. Can you assign this task to me?

**Comment by azakolyukina** [comment] 2017-08-17 16:56
@jingyujzhang: 

Could you please download the exact data that is specified in the issue. I do not see the data that I asked you to download.

**Comment by azakolyukina** [comment] 2017-08-17 20:16
@jingyujzhang (CC @iangow):

I think we should drop columns with the following prefixes when importing `audit` data since these data are in Compustat:
* `HIWATER_`
* `LATESTFY_`
* `LATESTQU_`
* `MATCHFY_`
* `MATCHQU_`
* `PRIORFY_`
* `PRIORQU_`

**Comment by jingyujzhang** [comment] 2017-08-18 03:56
@iangow : I noticed that in your update_audit.py, after calling wrds_update to pull data from wrds to pg, you will change some columns' data type manually. However, it seems that you don't change all of them to the ideal type. For example, cols `is_XXX` are clearly boolean, but only some cols are changed to boolean. Is this because you know only the cols with data type adjusted are useful while the others are not important, so you choose to leave them there for the moment? It would be much easier if we don't need to change all cols in the original dataset as wrds only has `CHAR`, `DATE` and `NUM`. Setting all cols to the correct data type would be relatively complex.

**Comment by iangow** [comment] 2017-08-18 04:21
I think the answer to your question is "yes"; only if I use the field did it seem worthwhile (I guess) to change data type. It might be worthwhile to do the conversion for the Audit Analytics `is_` variables if there are several of them, as it probably isn't too difficult to make code inside `update_audit.py` to do this. Also, we doing more work for the `audit` tables already. (For this reason, it might be worth having an `audit`-specific readme describing the tables in that schema.)

Another example is `permno` from `crsp`, which sometimes doesn't come through as an integer, so I used to have code to modify that variable explicitly.

**Comment by azakolyukina** [comment] 2017-08-18 23:04
@jingyujzhang: 

After you download the data, please check that WRDS date range is correct and check a few rows from `preview dataset` on WRDS to make sure there is no bug on data import.

**Comment by jingyujzhang** [comment] 2017-08-19 22:24
@iangow : While download table audit.nt, I met this error. It implies that line 5945 lacks a column (`best_efgar_ticker` is the last col).
> psycopg2.DataError: missing data for column "best_edgar_ticker"
> CONTEXT:  COPY nt, line 5945: "32941,2006-09-30,0,0,0,0,,,"Fannie Mae (formally, the Federal National Mortgage Association) > has det..."

I then grabbed the csv file `wrds_fetch.py` downloaded from wrds. On this row (`nt_notify_key = 32941`), the code **failed to pull the last 15 cols from wrds**.   

The affected cols are `file_size, http_name_html, http_name_text, ac_file_fkey, ac_form_fkey, ac_file_date, ac_file_accepted, ac_file_size, ac_http_name_html, ac_http_name_text, nt_reas_keys, nt_reas_titles, nt_reas_descrip, company_fkey, best_edgar_ticker`.   

All cols after `fize_size` are NA except that `company_fkey` is correct. These cols should have value.

```
>>> list(df.ix[5944])[21:36]  <- This is the row after the incorrect row
['111 KB', '/Archives/edgar/data/310522/000095013307000808/0000950133-07-000808-index.htm', '/Archives/edgar/data/310522/000095013307000808/0000950133-07-000808.txt', 'edgar/data/310522/0000950133-07-003508.txt', '10-K', '2007-08-16', '16AUG2007:08:30:06', '5 MB', '/Archives/edgar/data/310522/000095013307003508/0000950133-07-003508-index.htm', '/Archives/edgar/data/310522/000095013307003508/0000950133-07-003508.txt', '|5|16|28|65|26|10|', '|Internal Control / Sarbanes Oxley (404 or 302) assessment issues|Insufficient time to prepare or review report|Restatement of financials pending|Z - Expense recording issues|Bankruptcy, litigation, contingency, non-compliance of credit agreement|Material Weakness issues with ICFR or DC preparation|', '|The delay in the filing of the periodic report is attributable to difficulties surrounding the implementation of controls and procedures required to meet disclosure requirements pursuant to section 302 or section 404 of the Sarbanes-Oxley Act of 2002.|More time is needed to complete the periodic report.|Registrant has identified a restatement possible or definite.|Registrant has identified accounting issues associated with the expenses.|Registrant identifies pending litigation, a bankruptcy, or non-compliance of debt agreement terms (indebtedness).|Registrant identifies a material weakness in internal controls over financial reporting/disclosure controls.|', 310522.0, 'FNMA']
>>> list(df.ix[5943])[21:36]  <- This is the incorrect row
['112 KB', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 310522.0, nan] <- nan should have value
>>> list(df.ix[5942])[21:36]  <- This is the row before the incorrect row
['121 KB', '/Archives/edgar/data/310522/000095013306003655/0000950133-06-003655-index.htm', '/Archives/edgar/data/310522/000095013306003655/0000950133-06-003655.txt', nan, nan, nan, nan, nan, nan, nan, '|16|28|20|41|24|26|10|', '|Insufficient time to prepare or review report|Restatement of financials pending|Investigation underway, special committee (internal, external or SEC)|Liquidation or sale of assets|Change, newly hired, turnover, reduction or resignation of personnel, management, board, legal staff|Bankruptcy, litigation, contingency, non-compliance of credit agreement|Material Weakness issues with ICFR or DC preparation|', '|More time is needed to complete the periodic report.|Registrant has identified a restatement possible or definite.|The present undertaking of an internal or external investigation has delayed filing of the periodic report.  The SEC or a special committee is often identified with the investigation.|Registrant identifies the sale and/or liquidation of assets delayed the timely completion of the periodic filing.|The recent dismissal, resignation, reduction, turnover, and/or hiring of new personnel delayed the filing of the periodic report.|Registrant identifies pending litigation, a bankruptcy, or non-compliance of debt agreement terms (indebtedness).|Registrant identifies a material weakness in internal controls over financial reporting/disclosure controls.|', 310522.0, 'FNMA']
```
However, the query result from wrds using SAS doesn't seem to be abnormal.

```
   NT_NOTIFY_    FILE_
   Obs    KEY        SIZE

  5940       3254    73 KB
  5941        541    93 KB
  5942       7239    156 KB
  5943      15264    105 KB
  5944      24141    121 KB
  5945      32941    112 KB  <- Downloaded successfully
  5946      41349    111 KB

   Obs HTTP_NAME_HTML

  5940 /Archives/edgar/data/310522/000095013305003614/0000950133-05-003614-index.htm
  5941 /Archives/edgar/data/310522/000095013305005102/0000950133-05-005102-index.htm
  5942 /Archives/edgar/data/310522/000095013306001175/0000950133-06-001175-index.htm
  5943 /Archives/edgar/data/310522/000095013306002340/0000950133-06-002340-index.htm
  5944 /Archives/edgar/data/310522/000095013306003655/0000950133-06-003655-index.htm
  5945 /Archives/edgar/data/310522/000095013306004772/0000950133-06-004772-index.htm  <- Missing
  5946 /Archives/edgar/data/310522/000095013307000808/0000950133-07-000808-index.htm
```

1. I called `wrds_fetch.py` to download the other six tables and all tables are fine. 

2. Extra comma is not the reason. The higly suspected two cols are `http_name_html` (the first missing col) and `best_edgar_ticker` (the following/last col after `company_fkey` which is downloaded successfully). Unfortunately, these two cols are neat and clean, with no comma or extra whitespace.  

3. The rows around this missing-col-row experience very similiar situations like being blank for several rows, but they can be downloaded normally.  

4. The SAS code used to download data from wrds is listed as below. All the modification it does is to change NA to ".". But in the original dataset, these columns are not NA, so it might not be the reason.
```sas
options nosource nonotes;

libname pwd '/sastemp';

* Fix missing values;
data pwd.auditnt;
    set audit.nt(drop=matchfy: matchqu: priorfy: priorqu: );

    * dsf_fix;


    * fix_cr_code;


    array allvars _numeric_ ;

    do over allvars;
      if missing(allvars) then allvars = . ;
    end;
run;

* fund_names_fix;


proc export data=pwd.auditnt outfile=stdout dbms=csv;
run;
```
I can't think of other possibilities at the moment. And meanwhile, I can't bypass this problem as it is not caused by further modification, the data downloaded is incorrect. Any suggestions would be highly appreciated. Thanks.

**Comment by iangow** [comment] 2017-08-20 23:11
I will move `nt` to a new, separate issue. Please commit the code that you have (for all tables).

**Comment by jingyujzhang** [comment] 2017-08-21 03:16
I pushed the code to my forked repo. Two files `wrds_fecth.py` and `update_audit.py` are changed. All the tables except `nt` are fine. I checked the data range and some rows. The content was correct.  

However, I did find a small decoding problem.
```sql
select *
from audit.auditsox404
where ic_op_fkey = 19323  
```
Column `ic_text2` is as follows. I believe this is merely a supporting column so we can leave it there.
> "Managements Report on Internal Control Over Financial Reporting        Our management is responsible for establishing and > maintaining adequate internal control over financial reporting as defined in Rules 13a-15(f) and 15d-15(f) under the Securities > Excha (...)"

**Comment by iangow** [comment] 2017-08-21 03:32
> However, I did find a small decoding problem.

Yes. My code assumes (like WRDS) that the WRDS data is all `Latin1`, but some times this isn't true. WRDS doesn't appear to exert any effort checking the encoding of text and thus these issues slip through.

Perhaps we could create a new issue (say, "correct encoding issues with Audit Analytics data") and resolve them at some point in the future. I'd guess that Audit Analytics uses the same encoding for all data, so we'd just have to figure out what that is and how to make use of this information.

**Comment by iangow** [comment] 2017-08-28 22:44
@jingyujzhang 

When you run `./update_audit.py` do you not see this issue?

```bash
igow@igow-z640:~/git/wrds_pg$ export WRDS_ID=iangow
igow@igow-z640:~/git/wrds_pg$ echo $PGDATABASE 
crsp
igow@igow-z640:~/git/wrds_pg$ echo $PGHOST
localhost
igow@igow-z640:~/git/wrds_pg$ ./update_audit.py 
audit.auditnonreli already up to date
audit.bankrupt already up to date
Updated audit.diroffichange is available.
Getting from WRDS.

Beginning file import at 22:42:44.
Importing data into audit.diroffichange
Traceback (most recent call last):
  File "./update_audit.py", line 49, in <module>
    updated = wrds_update("diroffichange", "audit", engine, wrds_id, drop="match: prior: ")
  File "/home/igow/git/wrds_pg/wrds_fetch.py", line 350, in wrds_update
    drop=drop, obs=obs, rename=rename)
  File "/home/igow/git/wrds_pg/wrds_fetch.py", line 287, in wrds_to_pg
    res = wrds_process_to_pg(table_name, schema, engine, p)
  File "/home/igow/git/wrds_pg/wrds_fetch.py", line 318, in wrds_process_to_pg
    cursor.copy_expert(copy_cmd, p)
psycopg2.ProgrammingError: syntax error at or near ")"
LINE 1: COPY audit.diroffichange () FROM STDIN CSV ENCODING 'latin1'
                                  ^
```

**Comment by jingyujzhang** [comment] 2017-09-01 04:43
I tested it just now, and didn't meet the error you mentioned above for table `audit.diroffichange`. Actually the code works with `diroffichange`, `bankrupt` and `auditsox302` ( I randomly selected tables to update).

However, I do met this problem while trying to update `auditnonreli`. This table, according to the record you posted, you updated it successfully.

This is strange, as we succeeded and failed at **different tables**. 

> LINE 1: COPY audit.diroffichange () FROM STDIN CSV ENCODING 'latin1'

There should be a list of column names in `()`. Right now, the code fails to capture col names for some tables.

I will look into it further.

**Comment by jingyujzhang** [comment] 2017-09-01 06:33
Now I believe the problem for the failed tables is that SAS fails to download source data from wrds. The download process can be done as long as `drop` is set to `None`.

While I remove the `drop` restriction, I met the same problem that failed table `nt`. Luckily, now I know the reason. This is because by adding `drop`, we filter many irrelevant cols, and these cols contain a lot of text. These text are not all encode by `latin1`, and some of them are `utf-8`. The failure of  table `nt` is caused by decoding, I mentioned it in one of the comments above, but at that time, I didn't think it was huge.

Will continue working on it tomorrow.

**Comment by iangow** [comment] 2017-09-01 06:56
OK. Great. That is helpful. I think the Audit Analytics data might really be UTF-8 even though SAS thinks it's Latin1. I think that by setting the encoding somewhere in the code, this can be corrected. I did a little R&D on this issue; I need to check if I pushed the code (perhaps to a different branch).

But I'm not sure why "drop" is affecting things in this way (i.e., leading to no columns).

**Comment by iangow** [comment] 2017-09-01 07:22
So there is some code [here](https://github.com/iangow/wrds_pg/compare/encoding?expand=1) that relates to encoding issues. I can't recall whether it solves the issues for the `audit` data or not. But in any case, setting encoding to `utf-8` might solve it for those data and create problems for other data that *is* encoded as Latin1. So it might be best to add an `encoding` option to the `wrds_update` function with a default of `latin1`.

**Comment by jingyujzhang** [comment] 2017-09-06 05:37
I uploaded a new version of `update_audit.py` to my own repo. This version works, except for table `nt`.

**Comment by iangow** [comment] 2017-09-06 05:47
Thanks. I will give it a try sometime soon.

**Comment by iangow** [comment] 2017-09-06 06:58
Actually, you didn't push any code recently. According to Github:

>  **iangow:master** is up to date with all commits from **jingyujzhang:master**.

**Comment by jingyujzhang** [comment] 2017-09-06 18:41
Sorry for that. I've got too many `wrds` repo in my local dir. I committed `update_audit.py` again. Running it takes some time.

For table `nt`, I deleted cols with `drop="matchfy: matchqu: priorfy: priorqu: http: nt: ac:"` and this one works. So next I can just find ways to add back the these cols.

The `utf-8` version of `wrds_fetch.py` doesn't work for `nt`. Bytes like `0x92` exist in the file, these belong to `cp1252`.

**Comment by iangow** [comment] 2017-09-07 08:54
I got this working. The issue appeared to be `/sastemp` filling up. So I removed that and just used the SAS working directory and all seems fine now.

**Closed by iangow** 2017-09-07 08:54 UTC

**Comment by iangow** [comment] 2017-09-07 08:56
But I could not solve the issues with `audit.nt`. I think there are issues due to very long text fields, which don't get exported cleanly by `PROC EXPORT`.

**Comment by azakolyukina** [comment] 2017-09-07 22:45
What do we do with `audit.nt` then? I probably have just pull required fields from `WRDS`

**Comment by iangow** [comment] 2017-09-07 23:37
I think we only worry about this if we need variables that aren't on the reduced form of `audit.nt` that we have. The worst-case scenario is that we write a script to grab the SAS data file and use something like StatTransfer to convert to a form that we could read into PostgreSQL, perhaps via R or Python.

I think the issues are in parse of large text fields.
